# server:
#   port: 8082  # API Gateway port

# spring:
#   cloud:
#     gateway:
#       routes:

#         # 1. API routes (JSON endpoints)
#         - id: api-route
#           uri: http://localhost:8080
#           predicates:
#             - Path=/api/**  # backend APIs
#           filters:
#             - RewritePath=/api/(?<segment>.*), /api/${segment}

#         # 2. Public Pages (HTML + CSS + JS + images)
#         - id: frontend-route
#           uri: http://localhost:8080
#           predicates:
#             - Path=/**  # all frontend paths
#           filters:
#             - RewritePath=/(?<segment>.*), /${segment}  # forward /index → /index.html, /css/... → /css/...
# server:
#   port: 8082  # API Gateway port

# spring:
#   cloud:
#     gateway:
#       routes:
#         # Route for all frontend pages and static assets
#         - id: frontend-route
#           uri: http://localhost:8080
#           predicates:
#             - Path=/**       # Forward all requests
#           filters:
#             - RewritePath=/(?<segment>.*), /${segment}  # Keep paths as is

server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: frontend-route
          uri: ${SCHOOL_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/**   # Forward all requests
