spring.application.name=apiGetway
server.port=8082

spring.cloud.gateway.routes[0].id=school-service

spring.cloud.gateway.routes[0].predicates[0]=Path=/**
spring.cloud.gateway.routes[0].uri=${SCHOOL_SERVICE_URL:http://localhost:8080}