# FROM maven:3.9.9-eclipse-temurin-17 AS build

# WORKDIR /workspace

# COPY pom.xml .
# COPY src src

# RUN mvn -B -DskipTests package

# FROM eclipse-temurin:17-jre

# WORKDIR /app

# RUN mkdir -p /app/logs

# COPY --from=build /workspace/target/apiGetway-0.0.1-SNAPSHOT.jar app.jar

# EXPOSE 8082

# ENTRYPOINT ["java", "-jar", "app.jar"]
FROM maven:3.9.9-eclipse-temurin-17

WORKDIR /workspace

COPY pom.xml /workspace/pom.xml
COPY apiGetway/pom.xml /workspace/apiGetway/pom.xml
COPY School/pom.xml /workspace/School/pom.xml

RUN mvn -B -pl apiGetway -am dependency:resolve -DskipTests

WORKDIR /workspace/apiGetway

EXPOSE 8082

ENTRYPOINT ["mvn", "spring-boot:run", \
  "-Dspring-boot.run.jvmArguments=-Dspring.devtools.restart.enabled=true", \
  "-Dspring.devtools.restart.poll-interval=2s", \
  "-Dspring.devtools.restart.quiet-period=1s"]