# Application name and port
spring.application.name=first_app
server.port=8080

# Datasource (SQL Server)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=School;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:SA}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mariam@123}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
# seed.force=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

# Fix for JSR-310 converters (Hibernate 6 compatibility)
spring.data.jpa.repositories.enabled-context-converters=false

# Logging
logging.file.name=${LOGGING_FILE_NAME:logs/app.log}
logging.level.root=INFO
