# Application name and port
spring.application.name=first_app
server.port=8080

# Datasource (SQL Server)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=School;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:SA}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mariam@123}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
# seed.force=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
# Fix for JSR-310 converters (Hibernate 6 compatibility)
spring.data.jpa.repositories.enabled-context-converters=false

# Logging
logging.file.name=${LOGGING_FILE_NAME:logs/app.log}
logging.level.root=INFO

# Prevent Jackson from serializing Hibernate proxies
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false

# Ignore lazy loading issues
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=misrshoryanelataa@gmail.com
spring.mail.password=waid thog jxkd fsdx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true


spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
-Dspring.devtools.restart.enabled=true